{
	"version": 1516246783,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/player-sheet0.png",
		"images/invisiblesolid.png",
		"images/crystal-sheet0.png",
		"images/plataforma.png",
		"images/texto.png",
		"images/food-sheet0.png",
		"images/box-sheet0.png",
		"images/box-sheet1.png",
		"images/enemy-sheet0.png",
		"images/playersprites-sheet0.png",
		"images/playersprites-sheet1.png",
		"images/cleft-sheet0.png",
		"images/cright-sheet0.png",
		"images/cup-sheet0.png",
		"images/cpause-sheet0.png",
		"images/cpause-sheet1.png",
		"images/locked-sheet0.png",
		"images/tilemap.png",
		"images/cmenu-sheet0.png",
		"images/button-sheet0.png",
		"images/hearts.png",
		"images/tilesolids.png",
		"images/up-sheet0.png",
		"images/down-sheet0.png",
		"images/sprtright-sheet0.png",
		"images/sprtleft-sheet0.png",
		"images/enemyspikes-sheet0.png",
		"images/enemy2-sheet0.png",
		"images/sprite-sheet0.png",
		"images/kelua-sheet0.png",
		"images/kelua-sheet1.png",
		"images/sprite3-sheet0.png",
		"images/play-sheet0.png",
		"images/play-sheet1.png",
		"images/play-sheet2.png",
		"images/sprite10-sheet0.png",
		"images/tiledbackground3.png",
		"images/tiledbackground6.png",
		"images/tiledbackground4.png",
		"images/tiledbackground7.png",
		"images/sprite2-sheet0.png",
		"images/sprite19-sheet0.png",
		"images/sprite22-sheet0.png",
		"images/ulang-sheet0.png",
		"images/ulang-sheet1.png",
		"images/sprite25-sheet0.png",
		"images/sprite27-sheet0.png",
		"images/tiledbackground.png",
		"images/loding.png",
		"media/sfx5.m4a",
		"media/sfx5.ogg",
		"media/upgrade1.m4a",
		"media/upgrade1.ogg",
		"media/sword swing.m4a",
		"media/sword swing.ogg",
		"media/sfx1.m4a",
		"media/sfx1.ogg",
		"media/squaremotif1.m4a",
		"media/squaremotif1.ogg",
		"media/ui1.m4a",
		"media/ui1.ogg",
		"media/lazer ricochet.m4a",
		"media/lazer ricochet.ogg",
		"media/mattoglseby - 3.m4a",
		"media/mattoglseby - 3.ogg",
		"media/futuresynth2.m4a",
		"media/futuresynth2.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}